const en = {
  address: 'Address',
  bankAccountDetails: 'Bank Account Details',
  bankAccountHolderName: "Bank Account Holder's Name",
  bankAccountNumber: 'Bank Account Number',
  buttonYouAgree: 'button, you agree',
  businessAddressDetails: 'Business Address Details',
  byClickingThe: 'By clicking the',
  cart: 'Cart',
  changePassword: 'Change Password',
  chooseProducts: 'Choose Products',
  city: 'City',
  createAccount: 'Create Account',
  createAnAccount: 'Create An Account',
  createAnAccountLineBreak: 'Create an\nAccount',
  confirmPassword: 'ConfirmPassword',
  country: 'Country',
  emailAddress: 'Email Address',
  forgotPassword: 'Forgot Password?',
  getYourOrder: 'Get Your Order',
  iAlreadyHaveAnAccount: 'I Already Have an Account',
  ifscCode: 'IFSC Code',
  login: 'Login',
  makePayment: 'Make Payment',
  password: 'Password',
  personalDetails: 'Personal Details',
  pincode: 'Pincode',
  proceed: 'Proceed',
  register: 'Register',
  save: 'Save',
  signup: 'Sign Up',
  state: 'State',
  stylish: 'Stylish',
  toThePublicOffer: 'to the public offer',
  username: 'Username',
  userNameOrEmail: 'Username or Email',
  welcomeBack: 'Welcome\nBack!',
} as const

export default en

// Extracts the keys of translations words as a TypeScript type
export type enKeys = keyof typeof en
