import SpecialOffer from '../screens/core/home/SpecialOffer'

const en = {
  address: 'Address',
  allFeatured: 'All Featured',
  bankAccountDetails: 'Bank Account Details',
  bankAccountHolderName: "Bank Account Holder's Name",
  bankAccountNumber: 'Bank Account Number',
  buttonYouAgree: 'button, you agree',
  businessAddressDetails: 'Business Address Details',
  buyNow: 'Buy Now',
  byClickingThe: 'By clicking the',
  cancel: 'Cancel',
  cart: 'Cart',
  changePassword: 'Change Password',
  checkout: 'Checkout',
  continue: 'Continue',
  chooseProducts: 'Choose Products',
  city: 'City',
  createAccount: 'Create Account',
  createAnAccount: 'Create An Account',
  createAnAccountLineBreak: 'Create an\nAccount',
  confirmPassword: 'ConfirmPassword',
  country: 'Country',
  dealOfTheDay: 'Deal of the Day',
  deliveryAddress: 'Delivery Address',
  emailAddress: 'Email Address',
  filter: 'Filter',
  forgotPassword: 'Forgot Password?',
  getYourOrder: 'Get Your Order',
  goToCart: 'Go To Cart',
  iAlreadyHaveAnAccount: 'I Already Have an Account',
  ifscCode: 'IFSC Code',
  login: 'Login',
  makePayment: 'Make Payment',
  password: 'Password',
  personalDetails: 'Personal Details',
  pincode: 'Pincode',
  proceed: 'Proceed',
  register: 'Register',
  save: 'Save',
  searchAnyProduct: 'Search any Product...',
  signup: 'Sign Up',
  sort: 'Sort',
  specialOffers: 'Special Offers',
  specialOffersText: `We make sure you get the\noffer you need at best prices`,
  state: 'State',
  stylish: 'Stylish',
  toThePublicOffer: 'to the public offer',
  trendingProduct: 'Trending Products',
  username: 'Username',
  userNameOrEmail: 'Username or Email',
  viewAll: 'View All',
  welcomeBack: 'Welcome\nBack!',
} as const

export default en

// Extracts the keys of translations words as a TypeScript type
export type enKeys = keyof typeof en
