export default Object.freeze({
  BUYNOW: 'Buy Now',
  CART: 'Cart',
  CHANGEPASSWORD: 'Change Password',
  CHECKOUT: 'Checkout',
  CONFIRMATION: 'Confirmation',
  HOME: 'Home',
  LOGIN: 'Login',
  PRESENTATION: 'Presentation',
  PRODUCT: 'Product',
  PRODUCT_DETAILS: 'Product Details',
  PROFILE: 'Profile',
  REGISTER: 'Register',
  SEARCH: 'Search',
  SHOPPING_CART: 'ShoppingCart',
  SIGNUP: 'Signup',
  WELCOME: 'Welcome',
  WHISHLIST: 'Whishlist',
})
